POST http://localhost:3333/subscriptions
Content-Type: application/json

{
  "name": "Jessica Adamek",
  "email": "teste@teste.com.br"
}

###

GET http://localhost:3333/invites/4b7b21d9-2b3a-4146-89a0-60467275ae6a
